### ISSUE TITLE
EXT:metadata prevents adding other custom columns

### ISSUE THREAD

**Issue by hirnsturm** [fabarea/metadata#17]
If EXT:metadata is installed I can't see my custom added columns in file mata data TCA.

I add my columns like this in *sys_file_metadata.php*:
```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns(
    'sys_file_metadata',
    [
        'myField' => [
            'exclude' => 0,
            'label'   =>'myFieldLabel',
            'config'  => [
                'type' => 'input',
                'size' => 30,
                'max'  => 1000,
                'eval' => 'trim',
            ],
        ],
    ]
);

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
    'sys_file_metadata',
    ', --div--;myDivLabel, myField,',
    '',
    'after'
);
```

The reason is, that EXT:metadata uses *ArrayUtility::mergeRecursiveWithOverrule* in *metadata/Configuration/TCA/Overrides/sys_file_metadata.php*
```
\TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule($GLOBALS['TCA']['sys_file_metadata'], $tca);
```

**Comment by andre-spindler** [comment]
The same for me. Instead of using the TYPO3 API the metadata extension just overwrites the existing configuration.
I've contacted the extension author already two years ago (may 2015 I think), but nothing happens.

A workaround is to add "metadata" to the dependencies of you own extensions. Then it will be loaded before you own TCA additions. It works, but is far away from a good and stable solution.

**Comment by hirnsturm** [comment]
Thanks. Now I use [EXT:extractor](https://typo3.org/extensions/repository/view/extractor).

**Comment by fabarea** [comment]
@hirnsturm @andre-spindler If you add EXT:metadata as a dependency to your extension it should be loaded after EXT:metadata and the TCA should be good, no?

What do you suggest otherwise? Directly manipulating the `$GLOBALS['TCA']['sys_file_metadata']` without `mergeRecursiveWithOverrule` would work for you?
